### ISSUE TITLE
[REFECTOR] Login 기능

### ISSUE THREAD

**Issue by 2004yyj** [woowa-techcamp-2022/android-repo-02#54]
## 개요
- Token Value 가져오는 코드를 코루틴 Flow를 활용하도록 수정
- Main에서 Back Button 누를 시 Stack이 남아있지 않도록 수정
## 수정 사항
- Domain 단의 GetGitHubAccessTokenUseCase에서 Result 모델을 활용하여 Flow를 리턴하며 오류 찾기
- ViewModel에서는 LiveData 말고 SharedFlow 또는 StateFlow를 활용하고 성공/실패 Flow를 나눔
- AndroidManifest.xml의 LoginActivity 관련 태그에 android:noHistory 애트리뷰트를 true로 설정

**Comment by YM-Byun** [comment]
comment test
